name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
    
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: 3runoWilliam
          svg_out_path: dist/github-snake.svg, dist/ocean.gif?color_snake=black&color_dots=#bfd6f6
          
          <picture>
            <source media="(prefers-color-scheme: dark)" srcset="github-snake-dark.svg" />
            <source media="(prefers-color-scheme: light)" srcset="github-snake.svg" />
            <img alt="github-snake" src="github-snake.svg" />
          </picture>

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
